### ISSUE TITLE
Where no Room Thermostat is used, Wunda take an average of TRVs for temperature

### ISSUE THREAD

**Issue by mutasim** [tonyroberts/hawundasmart#1]
**Current Behaviour:**
No room thermostat associated with a room results in the climate sensor showing 0 for temp and 0 for humidity.

<img width="487" alt="image" src="https://github.com/tonyroberts/hawundasmart/assets/365801/78c30af0-1092-4f44-8365-a6a7921b9f4b">

**Expected Behaviour:**
Match the Wunda app. When no room thermostat is available, an average of the TRV temperatures are used and the humidity is null/hidden

![IMG_76422B07BDC6-1](https://github.com/tonyroberts/hawundasmart/assets/365801/52ec5775-7a4f-42ec-a5fa-33a1031dab89)

**Context:**

TRVs from syncvalues.cgi
```
32;1699602272;s:1;t:TH3K;v:1.2;vpos:0;vtemp:17.90;bat:100;sig:100;room_id:2;vpos_min:10;vpos_range:40;downforce:0;alarm:0;trv_range:680;
33;1699602273;s:1;t:TH3K;v:1.2;vpos:0;vtemp:19.60;bat:100;sig:88;room_id:2;vpos_min:5;vpos_range:40;downforce:0;alarm:0;trv_range:580;
```

Room from syncvalues.cgi
`123;1699602318;t_lo:17.00;t_norm:19.00;t_hi:25.00;heat:4;temp_pre:4;prg:0;lock:0;temp:0.00;ntemp:-1.00;ntime:0;es_avgtime:0;zone:2;relays:0;hb0:0;hb1:0;enable:123;tmax:27;tmaxh:5;settime:7200;pic:1;loc_in:1;loc_out:3;alarm:0;name:FF%20Hallway;tbl:000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000;`

**Comment by tonyroberts** [comment]
@mutasim I've just pushed some changes to fix this. I don't have a room without a thermostat to test this so let me know if this works for you.

**Comment by mutasim** [comment]
Can confirm - working as expected.
