### ISSUE TITLE
Manually setting a room to 'Off' should reflect in the climate mode

### ISSUE THREAD

**Issue by mutasim** [tonyroberts/hawundasmart#2]
**Current Behaviour:**
Given a room has been manually set to off (in the Wunda app), 
the target temperature correctly pulls through to the climate sensor as 0,
however the climate mode is set to 'heat'

**Expected Behaviour:**
Given a room has been manually set to off (in the Wunda app), 
the target temperature should pull through to the climate sensor as 0,
and the climate mode should be set to 'off'

**Comment by tonyroberts** [comment]
@mutasim could you confirm what the tp/temp_pre flags are showing as for you in this state please? I'd expect it to be 4 when manually set to off

**Comment by tonyroberts** [comment]
Never mind, I see the problem I think :)

**Comment by tonyroberts** [comment]
@mutasim this commit should fix it, let me know how you get on.

**Comment by mutasim** [comment]
Working as per the reported issue above. 👍

I've spotted that the hvac_action can appear out of sync from the mode, will raise it as a separate issue though

**Comment by tonyroberts** [comment]
@mutasim re hvac_action being different from hvac_mode, that's expected (but may be a limitation of my knowledge of what these things are supposed to represent in ha,

Here's the bit of code that sets both:

```
                # tp appears to be the following flags:
                # - 00000001 (0x01) indicates a manual override is set until the next manual override
                # - 00000100 (0x04) indicates the set point temperature has been set to 'off'
                # - 00010000 (0x10) indicates a manual override has been set
                # - 00100000 (0x20) indicates heating demand
                # - 10000000 (0x80) indicates the adaptive start mode is active
                flags = int(state["temp_pre"])
                self._attr_hvac_mode = (
                    HVACMode.OFF if flags & (0x10 | 0x4) == (0x10 | 0x4)  # manually set to off
                    else HVACMode.HEAT if (flags & (0x10 | 0x80)) == 0x10  # manually set to heat
                    else HVACMode.AUTO
                )
                self._attr_hvac_action = (
                    HVACAction.PREHEATING if ((flags & (0x80 | 0x20)) == (0x80 | 0x20))
                    else HVACAction.HEATING if flags & 0x20 
                    else HVACAction.OFF
                )
```

hvac_action is only set to heating if there is currently heating demand, whereas hvac_mode will indicate heat if the heating's been manually turned on (which may not result in demand if the set temperature is already above the requested temperature).

If you know how these things are supposed to be used, or can point me to some docs, I can update this logic.

**Comment by mutasim** [comment]
I've had a go at articulating my take on the issue at #3. I think it's a case of checking the 'hvac_action' value when mode is changed.
