### ISSUE TITLE
Time-bound manual heating level

### ISSUE THREAD

**Issue by mutasim** [tonyroberts/hawundasmart#20]
The Wunda app allows for Wunda room schedules to be overridden with a set temp for a set time. 

This is great for boosting a room's temp for a few hours but not worrying about returning it to the schedule.

Would be great if a service allowed for this behaviour to be exposed to Hass.

**Comment by tonyroberts** [comment]
That can be done using a Timer (https://www.home-assistant.io/integrations/timer/). It doesn't belong in the climate integration in HA, as that would mean all climate integrations would have to implement the same feature - better to use the existing functionality of HA than reinvent it in this project IMHO.
